const wordBtn = document.getElementById('wordBtn')
const input = document.getElementById('wordInput')
const resultText = document.getElementById('result')
const health = document.getElementById('health')
const victory = document.getElementById('victory')
const lose = document.getElementById('lose')
const nextBtn = document.getElementById('nextBtn')
const retryBtn = document.getElementById('retryBtn')
const message = document.getElementById('message')

const fiveLetterWords = [
  "about",
  "above",
  "actor",
  "admit",
  "adult",
  "after",
  "again",
  "agent",
  "agree",
  "ahead",
  "alarm",
  "album",
  "alert",
  "alive",
  "allow",
  "alone",
  "along",
  "among",
  "angle",
  "angry",
  "apple",
  "apply",
  "argue",
  "arise",
  "armor",
  "array",
  "arrow",
  "aside",
  "asset",
  "audio",
  "avoid",
  "award",
  "aware",
  "badly",
  "baker",
  "basic",
  "basis",
  "beach",
  "began",
  "begin",
  "being",
  "below",
  "bench",
  "bible",
  "birth",
  "black",
  "blade",
  "blame",
  "blank",
  "blind",
  "block",
  "blood",
  "board",
  "boost",
  "booth",
  "bound",
  "brain",
  "brake",
  "brand",
  "brave",
  "bread",
  "break",
  "breed",
  "brick",
  "bride",
  "brief",
  "bring",
  "broad",
  "broke",
  "brown",
  "brush",
  "build",
  "built",
  "bunch",
  "burst",
  "buyer",
  "cabin",
  "cable",
  "candy",
  "carry",
  "catch",
  "cause",
  "chain",
  "chair",
  "charm",
  "chart",
  "chase",
  "cheap",
  "cheat",
  "check",
  "chest",
  "chief",
  "child",
  "china",
  "chose",
  "claim",
  "class",
  "clean",
  "clear",
  "clerk",
  "click",
  "clock",
  "close",
  "cloth",
  "cloud",
  "coach",
  "coast",
  "color",
  "comic",
  "could",
  "count",
  "court",
  "cover",
  "crack",
  "craft",
  "crash",
  "cream",
  "crime",
  "cross",
  "crowd",
  "crown",
  "cycle",
  "daily",
  "dance",
  "death",
  "delay",
  "depth",
  "devil",
  "diary",
  "digit",
  "dirty",
  "doubt",
  "dozen",
  "draft",
  "drain",
  "drama",
  "dream",
  "dress",
  "drink",
  "drive",
  "drown",
  "dying",
  "eager",
  "early",
  "earth",
  "eight",
  "elect",
  "elite",
  "email",
  "empty",
  "enemy",
  "enjoy",
  "enter",
  "entry",
  "equal",
  "error",
  "essay",
  "event",
  "every",
  "exact",
  "exist",
  "extra",
  "faith",
  "false",
  "fault",
  "favor",
  "fence",
  "fever",
  "fewer",
  "fiber",
  "field",
  "fifth",
  "fifty",
  "fight",
  "final",
  "first",
  "flame",
  "flash",
  "fleet",
  "flesh",
  "float",
  "flood",
  "floor",
  "flour",
  "fluid",
  "focus",
  "force",
  "forth",
  "forty",
  "forum",
  "found",
  "frame",
  "frank",
  "fresh",
  "front",
  "fruit",
  "fully",
  "funny",
  "ghost",
  "giant",
  "given",
  "glass",
  "globe",
  "glory",
  "grade",
  "grain",
  "grand",
  "grant",
  "grape",
  "graph",
  "grass",
  "grave",
  "great",
  "green",
  "greet",
  "grief",
  "gross",
  "group",
  "guard",
  "guess",
  "guest",
  "guide",
  "habit",
  "happy",
  "harry",
  "harsh",
  "heart",
  "heavy",
  "hello",
  "hence",
  "honey",
  "honor",
  "horse",
  "hotel",
  "house",
  "human",
  "humor",
  "hurry",
  "ideal",
  "image",
  "imply",
  "index",
  "inner",
  "input",
  "issue",
  "ivory",
  "jewel",
  "joint",
  "judge",
  "juice",
  "knife",
  "knock",
  "known",
  "label",
  "labor",
  "large",
  "later",
  "laugh",
  "layer",
  "learn",
  "lease",
  "least",
  "leave",
  "legal",
  "level",
  "light",
  "limit",
  "local",
  "logic",
  "loose",
  "lower",
  "loyal",
  "lucky",
  "lunch",
  "lying",
  "magic",
  "major",
  "maker",
  "march",
  "marry",
  "match",
  "maybe",
  "mayor",
  "meant",
  "medal",
  "media",
  "metal",
  "meter",
  "might",
  "minor",
  "minus",
  "mixed",
  "model",
  "money",
  "month",
  "moral",
  "motor",
  "mount",
  "mouse",
  "mouth",
  "movie",
  "music",
  "naive",
  "naked",
  "nasty",
  "naval",
  "nerve",
  "never",
  "newly",
  "night",
  "noise",
  "north",
  "novel",
  "nurse",
  "occur",
  "ocean",
  "offer",
  "often",
  "older",
  "onion",
  "opera",
  "orbit",
  "order",
  "organ",
  "other",
  "ought",
  "ounce",
  "outer",
  "owner",
  "paint",
  "panel",
  "paper",
  "party",
  "paste",
  "patch",
  "pause",
  "peace",
  "penny",
  "phase",
  "phone",
  "photo",
  "piano",
  "piece",
  "pilot",
  "pitch",
  "place",
  "plain",
  "plane",
  "plant",
  "plate",
  "point",
  "pound",
  "power",
  "press",
  "price",
  "pride",
  "prime",
  "print",
  "prior",
  "prize",
  "proof",
  "proud",
  "prove",
  "pulse",
  "punch",
  "pupil",
  "purse",
  "queen",
  "query",
  "quest",
  "quick",
  "quiet",
  "quite",
  "quota",
  "quote",
  "radio",
  "raise",
  "rally",
  "ranch",
  "range",
  "rapid",
  "ratio",
  "reach",
  "react",
  "ready",
  "refer",
  "relax",
  "reply",
  "rhyme",
  "right",
  "rival",
  "river",
  "robot",
  "rough",
  "round",
  "route",
  "royal",
  "rural",
  "salad",
  "salty",
  "sandy",
  "sauce",
  "scale",
  "scare",
  "scene",
  "scent",
  "scope",
  "score",
  "screw",
  "sense",
  "serve",
  "setup",
  "seven",
  "shade",
  "shake",
  "shall",
  "shame",
  "shape",
  "share",
  "shark",
  "sharp",
  "sheep",
  "sheer",
  "sheet",
  "shelf",
  "shell",
  "shift",
  "shine",
  "shirt",
  "shock",
  "shoot",
  "shore",
  "short",
  "shout",
  "shown",
  "sight",
  "silly",
  "since",
  "sixth",
  "sixty",
  "skill",
  "skirt",
  "slave",
  "sleep",
  "slice",
  "slide",
  "slope",
  "small",
  "smart",
  "smell",
  "smile",
  "smoke",
  "snack",
  "snake",
  "solid",
  "solve",
  "sorry",
  "sound",
  "south",
  "space",
  "spare",
  "speak",
  "speed",
  "spell",
  "spend",
  "spice",
  "spirit",
  "split",
  "spoil",
  "sport",
  "staff",
  "stage",
  "stain",
  "stair",
  "stake",
  "stamp",
  "stand",
  "stare",
  "start",
  "state",
  "steak",
  "steal",
  "steam",
  "steel",
  "steep",
  "stick",
  "stiff",
  "still",
  "stock",
  "stone",
  "stood",
  "store",
  "storm",
  "story",
  "strap",
  "straw",
  "strip",
  "stuck",
  "study",
  "stuff",
  "style",
  "sugar",
  "suite",
  "super",
  "sweet",
  "swing",
  "sword",
  "table",
  "taken",
  "taste",
  "teach",
  "teeth",
  "tense",
  "tenth",
  "thank",
  "their",
  "theme",
  "there",
  "these",
  "thick",
  "thief",
  "thing",
  "think",
  "third",
  "those",
  "three",
  "throw",
  "tight",
  "timer",
  "title",
  "toast",
  "today",
  "token",
  "total",
  "touch",
  "tough",
  "towel",
  "tower",
  "toxic",
  "trace",
  "track",
  "trade",
  "trail",
  "train",
  "trash",
  "treat",
  "trend",
  "trial",
  "tribe",
  "trick",
  "tried",
  "troop",
  "truck",
  "truly",
  "trunk",
  "trust",
  "truth",
  "twice",
  "twist",
  "uncle",
  "under",
  "union",
  "unite",
  "unity",
  "until",
  "upper",
  "upset",
  "urban",
  "usage",
  "usual",
  "valid",
  "value",
  "video",
  "viral",
  "virus",
  "visit",
  "vital",
  "voice",
  "voter",
  "waste",
  "watch",
  "water",
  "weary",
  "weigh",
  "weird",
  "whale",
  "wheat",
  "wheel",
  "where",
  "which",
  "while",
  "white",
  "whole",
  "whose",
  "woman",
  "women",
  "world",
  "worry",
  "worse",
  "worst",
  "worth",
  "would",
  "wound",
  "wrist",
  "write",
  "wrong",
  "wrote",
  "yield",
  "young",
  "youth"
];

let healthPoint = 6
let randomNumber = Math.floor(Math.random() * fiveLetterWords.length)

health.innerText = healthPoint
const result = () => {
    message.innerText = ''
    if(input.value.length < 5){
        message.innerText = "Please input 5 length word"
        return
    } else if(fiveLetterWords.includes(input.value.toLowerCase()) === false) {
        message.innerText = "Please input proper word"
        return
    }
    if(healthPoint === 0){
        message.innerText = "You already lose!"
        return
    }

    const quiz = fiveLetterWords[randomNumber]
    
    healthPoint -= 1
    health.innerText = healthPoint

    let benar = 0
    let cekDouble = 0
    for(let i = 0; i < 5; i++){
        for(let j = 0; j < 5; j++){
            if(input.value[i].toLowerCase() === quiz[j] && i === j){
                benar += 1
                document.getElementById(`box${i+1}`).innerHTML += correct(input.value[i])
                cekDouble = 0
                break
            } else if(input.value[i].toLowerCase() === quiz[j] && i !== j){
                cekDouble += 1
            } else if(j === 4 && cekDouble === 0) {
                document.getElementById(`box${i+1}`).innerHTML += wrong(input.value[i])
            }
        }
        if(cekDouble > 0){
            document.getElementById(`box${i+1}`).innerHTML += halfCorrect(input.value[i])
        }
        cekDouble = 0
    }
    resultText.innerHTML += `<br>`
    input.value = ''
    if(benar === 5){
        victory.style.display = 'flex'
        return
    }
    if(healthPoint === 0){
        lose.style.display = 'flex'
        retryBtn.innerText = `Correct answer : ${quiz.toUpperCase()}. Click to try again.`
        return
    }
}

const correct = (char) => {
    return `<div class="bg-green-600 h-10 w-10 rounded-sm flex mx-0.5 my-1"><p class="my-auto mx-auto">${char.toUpperCase()}</p></div>`
}

const halfCorrect = (char) => {
    return `<div class="bg-yellow-500 h-10 w-10 rounded-sm flex mx-0.5 my-1"><p class="my-auto mx-auto">${char.toUpperCase()}</p></div>`
}

const wrong = (char) => {
    return `<div class="bg-red-700 h-10 w-10 rounded-sm flex mx-0.5 my-1"><p class="my-auto mx-auto">${char.toUpperCase()}</p></div>`
}

wordBtn.addEventListener('click', result)

input.addEventListener('keydown', (e) => {
    if(e.key === 'Enter'){
        result()
    }
})

const reset = () => {
    healthPoint = 6
    health.innerText = healthPoint
    for(let i = 0; i < 5; i++){
        document.getElementById(`box${i+1}`).innerHTML = ''
    }
    victory.style.display = 'none'
    lose.style.display = 'none'
    randomNumber = Math.floor(Math.random() * fiveLetterWords.length)
}

nextBtn.addEventListener('click', reset)
retryBtn.addEventListener('click', reset)
